version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  build:
    docker:
      - image: node:latest
    working_directory: /server
    steps: 
      - checkout
      - run: echo "may the force be with you"
      - run: pwd



